apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 120Gi 
  accessModes:
    - ReadWriteMany 
  mountOptions:
    - allow-delete
    - region eu-west-1  
    - prefix {{ .Release.Name }}/
  csi:
    driver: s3.csi.aws.com 
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: microservice-logs 